### ISSUE TITLE
In-memory cache improperly evicts fragment on root query type

### ISSUE THREAD

**Issue by andrew0** [apollographql/apollo-client#11404]
### Issue Description

I was doing some testing with the Star Wars API, and ran into some trouble with Apollo Client when querying a fragment on the root type. The in-memory cache seems to erroneously remove the fragments when diffing the cache (the removal occurs here: https://github.com/apollographql/apollo-client/blob/b9332e0e1910ab1ca8eb15af4a01327161047348/src/core/QueryInfo.ts#L456C1-L456C51). The issue goes away if I set a no-cache policy.

In my reproducer, I am making this query against the star wars API (https://swapi-graphql.netlify.app/.netlify/functions/index):

```gql
fragment Films on Root {
  allFilms(first: 1) {
    edges {
      node {
        title
      }
    }
  }
}

query getFilms {
  allPeople(first: 1) {
    edges {
      node {
        name
      }
    }
  }
  ...Films
}
```

The result I get from Apollo Client is:

```yaml
{
  "data": {
    "allPeople": {
      "__typename": "PeopleConnection",
      "edges": [
        {
          "__typename": "PeopleEdge",
          "node": {
            "__typename": "Person",
            "name": "Luke Skywalker"
          }
        }
      ]
    }
  },
  "loading": false,
  "networkStatus": 7
}
```

This appears to be a similar problem as https://github.com/apollographql/apollo-client/issues/3402. That issue was fixed, but it only seems to have fixed the case where the root query type is named `Query`. The Star Wars API uses the name `Root` for the root query type, which seems to trigger this problem.

### Link to Reproduction

https://github.com/andrew0/apollo-client-repro

### Reproduction Steps

1. Go to reproducer page https://andrew0.github.io/apollo-client-repro/
2. Look at console, and see the response from Apollo Client
