### ISSUE TITLE
`Out of stack space` error in IE 11

### ISSUE THREAD

**Issue by joelwatson** [apollographql/apollo-client#4067]
In IE 11, certain versions of `apollo-client` result in the following error:

```
Unhandled promise rejection Error: Network error: Out of stack space
```
![image](https://user-images.githubusercontent.com/9660362/47568554-04920400-d8f7-11e8-972b-c7a5185d2c0f.png)

In IE 11, `apollo-client 2.4.1` works as expected. However, the following versions produce the error above:

```
2.4.0
2.4.2
2.4.3 (latest)
```
I saw previous reports of this which suggested it might be related to needing a polyfill for `fetch`; however, I am currently using `unfetch` as recommended.

For the time being, I have reverted to `2.4.1`, but wanted to report it for a fix in future versions.

Please let me know if any additional information would be helpful.

**Versions**
```
npmPackages:
    apollo-cache-inmemory: ^1.2.8 => 1.2.8
    apollo-client: ^2.4.2 => 2.4.2
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-error: ^1.0.9 => 1.0.9
    apollo-link-state: ^0.4.1 => 0.4.1
    apollo-link-ws: ^1.0.8 => 1.0.8
    apollo-upload-client: ^8.1.0 => 8.1.0
    apollo-utilities: ^1.0.12 => 1.0.12
    react-apollo: ^2.1.3 => 2.1.4
```
