### ISSUE TITLE
graphql-codegen-fragment-matcher typescript error

### ISSUE THREAD

**Issue by Eraldo** [apollographql/apollo-client#4772]
**Intended outcome:**

`gql-gen` produces code without typescript errors.

**Actual outcome:**

I get compilation errors:
E.g.:
```
ERROR in src/types.ts(5828,5): error TS1005: ';' expected.

ℹ ｢wdm｣: Failed to compile.

ERROR in src/app/core/graphql/graphql.module.ts(61,35): error TS2304: Cannot find name 'introspectionResult'.
src/types.ts(5828,6): error TS2693: 'DayInterviewNodeInlineFragment' only refers to a type, but is being used as a value here.
src/types.ts(5828,39): error TS2693: 'WeekInterviewNodeInlineFragment' only refers to a type, but is being used as a value here.
```
Example generated code snippet:
```ts
  export type Interview = {
    __typename: DayInterviewNodeInlineFragment["__typename"] | WeekInterviewNodeInlineFragment["__typename"];
  } (DayInterviewNodeInlineFragment | WeekInterviewNodeInlineFragment)
```

Config:
```
#schema: ../schema.graphql
schema: http://local.domain.org/api/graphql
documents: ./src/**/*.graphql
overwrite: true
generates:
  ./src/types.ts:
    config:
      noGraphqlTag: true
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
      - fragment-matcher
```

**Versions**

```
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http": "^1.6.0",
    "apollo-angular-link-network-status": "^1.0.4",
    "apollo-cache-inmemory": "^1.5.1",
    "apollo-client": "^2.5.1",
    "apollo-link": "^1.2.11",
    "apollo-link-batch-http": "^1.2.11",
    "apollo-upload-client": "^10.0.0",
...
    "graphql-code-generator": "^0.18.1",
    "graphql-codegen-fragment-matcher": "^0.18.1",
    "graphql-codegen-introspection-template": "^0.18.1",
    "graphql-codegen-typescript-apollo-angular": "^0.18.1",
    "graphql-codegen-typescript-client": "^0.18.1",
    "graphql-codegen-typescript-common": "^0.18.1",
```

Did I maybe miss something or do something wrong?
Ideas how to get it to work?
