### ISSUE TITLE
Local variables cause server-side error (@client directive)

### ISSUE THREAD

**Issue by alex-golubtsov** [apollographql/apollo-client#6913]
Using variable only in local (client) query triggers server-side error. The details are in **_How to reproduce the issue section_**

**Intended outcome:**
No error is triggered

**Actual outcome:**
Server responds with the error `unexpected variables in variableValues: <variable_name>`

**How to reproduce the issue:**
```gql
query TestQuery ($id: Int, $color: String, $model: String) {
  ColorById (id: $id) @client @export(as: "color")
  Cars (model: $model, color: $color) {
    ....car data here
  }
}
```

In this case, the server throws an error `unexpected variables in variableValues: id`. And the reason is simple: the `$id` variable is being used only in local (client) query. Despite this fact server still receives the variable.

**Possible solution:**
Do not send (to the server) the variables, which are being used only in local queries/fields.

**Versions**
```yml
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.0
    Yarn: 1.22.4
    npm: 6.14.4
  Browsers:
    Chrome: 84.0.4147.125
  npmPackages:
    @apollo/client: ~3.1.2 => 3.1.3
    apollo: ~2.30.2 => 2.30.2
```
