### ISSUE TITLE
fetchMore and fetchPolicy: cache-and-network does not work together

### ISSUE THREAD

**Issue by alex-golubtsov** [apollographql/apollo-client#6916]
**Intended outcome:**
In case of `fetchMore` additional request should not be executed or should use last variables (passed to `fetchMore`)

**Actual outcome:**
The request executes with wrong variables

**How to reproduce the issue:**
```tsx
function MyComponent() {
  const q = useQuery(query, { variables: { offset: 0 }, fetchPolicy: 'cache-and-network' });
  ...
  <button id="button" onClick={() => q.fetchMore({ variables: { offset: 10 } })}>Click me</button>
}
```

That's what is happening:
1. `<MyComponent />` is rendered
           => request to the server is executed with `{ offset: 0 }`
2. Button `#button` clicked
           => request to the server is executed with `{ offset: 10 }`
           => request to the server is executed with `{ offset: 0 }`

In other words the request, which fetches fresh data from the server uses variables passed to the hook, but to to `fetchMore`

**Versions**

```yml
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.0
    Yarn: 1.22.4
    npm: 6.14.4
  Browsers:
    Chrome: 84.0.4147.125
  npmPackages:
    @apollo/client: ~3.1.2 => 3.1.3
    apollo: ~2.30.2 => 2.30.2
```
