### ISSUE TITLE
fetchMore does not use @export directive

### ISSUE THREAD

**Issue by alex-golubtsov** [apollographql/apollo-client#6923]
fetchMore does not use `@export` directive to query cache for the data
**Intended outcome:**
Variable defined with `@export` is being used

**Actual outcome:**
Variable defined with `@export` is not being used

**How to reproduce the issue:**

Assume we have the query (also let's assume `SelectedColor` returns `red`):
```gql
query TestQuery ($color: String, $model: String!) {
  SelectedColor @client @export(as: "color")
  Cars (model: $model, color: $color) {
    ....car data here
  }
}
```

and the component:
```tsx
function MyComponent() {
  const q = useQuery(query, { variables: { model: "bmw" } });
  ...
  <button id="button" onClick={() => q.fetchMore({ variables: { model: "bmw" } })}>Click me</button>
}
```

That's what is happening:

1. `<MyComponent />` is rendered
               => apollo queries cache with `{ model: "bmw", color: "red" }` as variables
2. Button `#button` clicked
               => apollo queries cache with `{ model: "bmw", color: undefined }` as variables

To verify this use following type policy:
```tsx
typePolicies: {
  Query:
    fields: {
      Cars: {
         keyArgs: (args) => {
            console.log(args) // this line shows the problem
            return ....
         },
         merge: ....
      }
    }
  }
}
```

**Versions**
```yml
 System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.0
    Yarn: 1.22.4
    npm: 6.14.4
  Browsers:
    Chrome: 84.0.4147.125
  npmPackages:
    @apollo/client: ~3.1.2 => 3.1.3
    apollo: ~2.30.2 => 2.30.2
```
