### ISSUE TITLE
Asynchronous headers for socket connection in React Native

### ISSUE THREAD

**Issue by BLOCKMATERIAL** [apollographql/apollo-client#9355]
**Intended outcome:**
Support for asynchronous methods to insert token into web socket headers.
**Actual outcome:**
 I can't pass my token received from AsyncStorage / EcnryptedStorage to web socket headers

**How to reproduce the issue:**
I'm trying to get and add my authorization token from the storage (AsyncStorage / EcnryptedStorage).Getting the token is asynchronous when announced I can not pass it to the headers.
I guess it happens because. connectionParams section is designed for non-asynchronous LocalStorage, but in React Native all the manupulations with data from the storage are asynchronous 
**Code:**
```
const wsLink = new WebSocketLink({
  uri: `wss://myLinkWebsocket`,
  options: {
    lazy: true,
    reconnect: true,
    connectionParams: async () => {
      const token = await EncryptedStorage.getItem('@access-token');
      return {
        authorization: token ? `Bearer ${token}` : '',
      };
    },
  },
});
```
**Versions**
   

```
  npmPackages:
    @apollo/client: 3.4.15 => 3.4.15 
    @apollo/react-hooks: ^4.0.0 => 4.0.0 
    apollo-boost: ^0.4.9 => 0.4.9 
    apollo-cache-inmemory: ^1.6.6 => 1.6.6 
    apollo-client: ^2.6.10 => 2.6.10 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-link-http: ^1.5.17 => 1.5.17 
    apollo-link-state: ^0.4.2 => 0.4.2 
    apollo-link-ws: ^1.0.20 => 1.0.20 
    apollo-upload-client: ^16.0.0 => 16.0.0 
    apollo-utilities: ^1.3.4 => 1.3.4 
    react-apollo: ^3.1.5 => 3.1.5 

```
